apiVersion: v1
kind: Service
metadata:
  name: secrets-postgres
  namespace: envini
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: secrets-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secrets-postgres
  namespace: envini
spec:
  serviceName: secrets-postgres
  replicas: 1
  selector:
    matchLabels:
      app: secrets-postgres
  template:
    metadata:
      labels:
        app: secrets-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: envini
            - name: POSTGRES_USER
              value: envini
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets-secret
  namespace: envini
stringData:
  password: envini
