apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-oauth-spc
  namespace: envini
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/envini/secrets/github-client-id/versions/latest"
        path: "client_id"
  secretObjects:
    - secretName: github-oauth-secret
      type: Opaque
      data:
        - objectName: client_id
          key: client_id
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: master-encryption-spc
  namespace: envini
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/envini/secrets/master-encryption-key/versions/latest"
        path: "key"
