# Use the official PostgreSQL image from Docker Hub
FROM postgres:16-alpine

# Set environment variables for the default user, password, and database
ENV POSTGRES_USER=envini
ENV POSTGRES_PASSWORD=envini
ENV POSTGRES_DB=envini

# Expose the default PostgreSQL port
EXPOSE 5432